name: Publish
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          curl -LSfs https://raw.githubusercontent.com/crate-ci/gh-install/master/v1/install.sh | \
            sh -s -- \
            --git cobalt-org/cobalt.rs \
            --crate cobalt \
            --force \
            --target x86_64-unknown-linux-gnu \
            --tag v0.19.6
          echo COBALT_BIN=~/.cargo/bin/cobalt >> $GITHUB_ENV

      - name: Build
        run: ${{ env.COBALT_BIN }} build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
